image: node:latest


stages:
  - install
  - build
 
  
# Jobs 
install_dependencies:
  stage: install
  script:
    - cd movies
    - npm ci --cache .npm --prefer-offline
    
  artifacts:
    paths:
      - movies/node_modules/

bundle_app:
  stage: build
  script:
    - cd movies
    - npm run build
  artifacts:
    paths:
      - movies/build/
   
