image: node:latest


stages:
  - install
  - build
 
  
# Jobs 
install_dependencies:
  stage: install
  script:
    - cd movies
    - npm ci --cache .npm --prefer-offline
    
  artifacts:
    paths:
      - movies/node_modules/

bundle_app:
  stage: build
  script:
    - cd movies
    - npm run build
  artifacts:
    paths:
      - movies/build/

e2etest:
# Node docker image with Cypress and Chrome pre-installed
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    - cd movies
    - echo "Run tests in headless mode"
    - npm run start:ci

build_jobX:
  stage: build
  only:
    - develop
  script:
    - cd movies
    - echo "build job X on demoBranch works"

test_jobX:
  stage: test
  only:
    - main
    - branchX
  script:
    - cd movies
    - echo "Run tests in headless mode"
    - npm run start:ci
   
